// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOjNgGFlrJm167kr3vqVArLpzMmjh7gcI',
    appId: '1:952466911914:web:4148f1d48b0264207c16d3',
    messagingSenderId: '952466911914',
    projectId: 'wordopol-7a16f',
    authDomain: 'wordopol-7a16f.firebaseapp.com',
    storageBucket: 'wordopol-7a16f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJtuiAwQIN3_1WkphvB74sPnuIkNo-fNw',
    appId: '1:952466911914:android:bf659311dd54be6f7c16d3',
    messagingSenderId: '952466911914',
    projectId: 'wordopol-7a16f',
    storageBucket: 'wordopol-7a16f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Ni_AjDTlJxRRVlHPOyO9Wq9Lm-goWUQ',
    appId: '1:952466911914:ios:4e082812b49d11217c16d3',
    messagingSenderId: '952466911914',
    projectId: 'wordopol-7a16f',
    storageBucket: 'wordopol-7a16f.appspot.com',
    iosClientId: '952466911914-qa9qhnf0805mbbjkjhnn80d05ufrvbd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.wordopol',
  );
}
